apiVersion: kubekey.kubesphere.io/v1
kind: Playbook
metadata:
  creationTimestamp: "2026-05-17T19:57:34Z"
  generateName: precheck-kubernetes-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
      f:spec:
        f:config:
          f:spec:
            f:cni:
              .: {}
              f:ipv4_mask_size: {}
              f:ipv6_mask_size: {}
              f:pod_cidr: {}
              f:service_cidr: {}
              f:type: {}
            f:cri:
              .: {}
              f:container_manager: {}
            f:image_registry:
              .: {}
              f:auth:
                .: {}
                f:insecure: {}
                f:password: {}
                f:registry: {}
                f:username: {}
              f:harbor:
                .: {}
                f:data_dir: {}
              f:type: {}
            f:kubernetes:
              .: {}
              f:cluster_name: {}
              f:control_plane_endpoint:
                .: {}
                f:host: {}
                f:kubelet:
                  .: {}
                  f:max_pods: {}
                f:port: {}
                f:type: {}
              f:kube_version: {}
            f:storage_class:
              .: {}
              f:nfs:
                .: {}
                f:default: {}
                f:enabled: {}
                f:path: {}
                f:server: {}
            f:work_dir: {}
        f:inventoryRef:
          .: {}
          f:kind: {}
          f:name: {}
          f:namespace: {}
        f:playbook: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:57:34Z"
  - apiVersion: kubekey.kubesphere.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:failureMessage: {}
        f:failureReason: {}
        f:phase: {}
        f:statistics:
          f:failed: {}
          f:ignored: {}
          f:success: {}
          f:total: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:59:30Z"
  name: precheck-kubernetes-wcz7c
  namespace: default
  resourceVersion: "2"
  uid: 1afcf250-955a-4ecd-9480-abc54ad95266
spec:
  config:
    spec:
      cni:
        ipv4_mask_size: 24
        ipv6_mask_size: 64
        pod_cidr: 10.233.64.0/18
        service_cidr: 10.233.0.0/18
        type: calico
      cri:
        container_manager: containerd
      image_registry:
        auth:
          insecure: true
          password: Harbor12345
          registry: harbor.rise.io
          username: admin
        harbor:
          data_dir: /data/registry
        type: harbor
      kubernetes:
        cluster_name: host-cluster
        control_plane_endpoint:
          host: lb.rise.io
          kubelet:
            max_pods: 110
          port: 6443
          type: local
        kube_version: v1.29.15
      storage_class:
        nfs:
          default: true
          enabled: true
          path: /data/share
          server: 47.253.179.114
      work_dir: /mnt/e/Openclaw/kk-console/kubekey
  inventoryRef:
    kind: Inventory
    name: default
    namespace: default
  playbook: web-installer/kubernetes/playbooks/precheck.yaml
  project: {}
status:
  failureMessage: "task [Network | Ensure required network interfaces are present](default/precheck-kubernetes-wcz7c-zrn9c)
    run failed: \n[47-253-179-114][executor]: module run failed\n[47-253-179-114][item=<nil>][0]:
    \nstdout: The specified IPv4 address is not assigned to any network interface.\nstderr:
    \nerror: Process exited with status 1\n"
  failureReason: task executor failed
  phase: Failed
  result: null
  statistics:
    failed: 1
    ignored: 2
    success: 38
    total: 41
