apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: .
  creationTimestamp: "2026-05-17T19:24:49Z"
  generateName: host-check-xvczx-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:ignoreError: {}
        f:module:
          f:args: {}
          f:name: {}
        f:name: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:24:49Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:25:09Z"
  name: host-check-xvczx-wts46
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: host-check-xvczx
    uid: 87714ec7-0837-4f9b-bc0c-a868fab89241
  resourceVersion: "3"
  uid: 19e7f837-c59c-4870-8907-703cd3a1d94e
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  ignoreError: true
  loop: null
  module:
    args: {}
    name: setup
  name: get host info
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: success
  phase: Success
