apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: .
  creationTimestamp: "2026-05-17T19:43:44Z"
  generateName: host-check-fjjcn-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args: {}
          f:name: {}
        f:name: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:43:44Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:43:44Z"
  name: host-check-fjjcn-8k6z5
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: host-check-fjjcn
    uid: 3df63913-356e-4bc5-8736-39564f724b35
  resourceVersion: "3"
  uid: e586ba16-1a96-4523-b1b5-a0e38005250e
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args: |
      {{- range $k,$v := .hostvars }}
      {{ $k }}:
        arch: "{{ if $.architectures.amd64 | has ($v.os.architecture | default "") }}amd64{{ else if $.architectures.arm64 | has ($v.os.architecture | default "") }}arm64{{ else }}{{ $v.os.architecture | default "" }}{{ end }}"
        hostname: "{{ $v.os.hostname | default "" }}"
      {{- end }}
    name: result
  name: set result
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: success
  phase: Success
