apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: .
  creationTimestamp: "2026-05-17T19:01:39Z"
  generateName: host-check-29gnq-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:ignoreError: {}
        f:module:
          f:args: {}
          f:name: {}
        f:name: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:01:39Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:01:59Z"
  name: host-check-29gnq-nm9ws
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: host-check-29gnq
    uid: df082309-326e-4d42-8bfb-bcd40c9604e2
  resourceVersion: "3"
  uid: a23f99d0-0fcb-4741-bb57-00a1c62fcd44
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  ignoreError: true
  loop: null
  module:
    args: {}
    name: setup
  name: get host info
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: success
  phase: Success
