apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: .
  creationTimestamp: "2026-05-17T19:34:37Z"
  generateName: host-check-crt6q-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:ignoreError: {}
        f:module:
          f:args: {}
          f:name: {}
        f:name: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:34:37Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:34:53Z"
  name: host-check-crt6q-zwxn6
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: host-check-crt6q
    uid: ecadcdb3-708c-462d-b794-cec4deeb6cab
  resourceVersion: "3"
  uid: 486feb3b-958b-4bde-8d7a-b6739a5fc318
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  ignoreError: true
  loop: null
  module:
    args: {}
    name: setup
  name: get host info
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: success
  phase: Success
