apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: .
  creationTimestamp: "2026-05-17T17:12:37Z"
  generateName: host-check-sz4wj-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args: {}
          f:name: {}
        f:name: {}
    manager: kk
    operation: Update
    time: "2026-05-17T17:12:37Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T17:12:37Z"
  name: host-check-sz4wj-tqph9
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: host-check-sz4wj
    uid: 0536d242-ab0e-4925-816d-bb3a93a64011
  resourceVersion: "3"
  uid: 520f6a3d-00f5-4021-b368-b5e7e464bb6a
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args: |
      {{- range $k,$v := .hostvars }}
      {{ $k }}:
        arch: "{{ if $.architectures.amd64 | has ($v.os.architecture | default "") }}amd64{{ else if $.architectures.arm64 | has ($v.os.architecture | default "") }}arm64{{ else }}{{ $v.os.architecture | default "" }}{{ end }}"
        hostname: "{{ $v.os.hostname | default "" }}"
        os: {{ $v.os.release.PRETTY_NAME | default "\"\"" }}
      {{- end }}
    name: result
  name: set result
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: success
  phase: Success
