apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: .
  creationTimestamp: "2026-05-17T18:56:40Z"
  generateName: host-check-pmmwv-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args: {}
          f:name: {}
        f:name: {}
    manager: kk
    operation: Update
    time: "2026-05-17T18:56:40Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T18:56:40Z"
  name: host-check-pmmwv-p5kc4
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: host-check-pmmwv
    uid: cc51b7da-a3fb-4a7d-8663-2861f28369c9
  resourceVersion: "3"
  uid: 52d58c27-5b0d-4bbd-9643-ccff6812ae25
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args: |
      {{- range $k,$v := .hostvars }}
      {{ $k }}:
        arch: "{{ if $.architectures.amd64 | has ($v.os.architecture | default "") }}amd64{{ else if $.architectures.arm64 | has ($v.os.architecture | default "") }}arm64{{ else }}{{ $v.os.architecture | default "" }}{{ end }}"
        hostname: "{{ $v.os.hostname | default "" }}"
        os: {{ $v.os.release.PRETTY_NAME | default "\"\"" }}
      {{- end }}
    name: result
  name: set result
status:
  hostResults:
  - error: module run failed
    host: 47-253-179-114
    loopResults:
    - error: |-
        failed to execute template '{{- range $k,$v := .hostvars }}
        {{ $k }}:
          arch: "{{ if $.architectures.amd64 | has ($v.os.architecture | default "") }}amd64{{ else if $.architectures.arm64 | has ($v.os.architecture | default "") }}arm64{{ else }}{{ $v.os.architecture | default "" }}{{ end }}"
          hostname: "{{ $v.os.hostname | default "" }}"
          os: {{ $v.os.release.PRETTY_NAME | default "\"\"" }}
        {{- end }}
        ': template: kubekey:3:46: executing "kubekey" at <$v.os.architecture>: can't evaluate field architecture in type interface {}
      item: null
      stdErr: failed to parse argument
      stdout: failed
  phase: Failed
