apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/defaults
  creationTimestamp: "2026-05-17T17:53:17Z"
  generateName: install-8g6zv-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args: {}
          f:name: {}
        f:name: {}
    manager: kk
    operation: Update
    time: "2026-05-17T17:53:17Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T17:53:18Z"
  name: install-8g6zv-tc678
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: install-8g6zv
    uid: 66d47053-b913-464d-8a85-4d05c9a55bbc
  resourceVersion: "3"
  uid: c54ee154-8dac-4e29-ba59-cafad65711f2
spec:
  DelegateTo: ""
  hosts:
  - localhost
  loop: null
  module:
    args: |
      if [ -d {{ .tmp_dir }} ]; then
        rm -rf {{ .tmp_dir }}
      fi
      mkdir -m 777 -p {{ .tmp_dir }}
    name: command
  name: Defaults | Reset temporary directory
status:
  hostResults:
  - host: localhost
    loopResults:
    - item: null
  phase: Success
