apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/native/dns
  creationTimestamp: "2026-05-17T20:23:01Z"
  generateName: install-j7l5w-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:loop: {}
        f:module:
          f:args: {}
          f:name: {}
        f:name: {}
    manager: kk
    operation: Update
    time: "2026-05-17T20:23:01Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T20:23:06Z"
  name: install-j7l5w-zq9s4
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: install-j7l5w
    uid: 4c66d514-df22-41f0-bd1c-723ae58e20e9
  resourceVersion: "3"
  uid: f682110f-26c6-4f81-9013-f291aac206b1
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: '{{ .native.localDNS | toJson }}'
  module:
    args: |
      # Clean up any previous Kubekey-managed DNS blocks
      sed -i '/# kubekey hosts BEGIN/,/# kubekey hosts END/d' {{ .item }}
      # Write the latest Kubekey DNS configuration
      cat >> {{ .item }} <<EOF
      # kubekey hosts BEGIN
      # Kubernetes cluster nodes
      {{- range .groups.k8s_cluster | default list }}
        {{- $hostname := index $.hostvars . "hostname" -}}
        {{- $clusterName := $.kubernetes.cluster_name | default "kubekey" -}}
        {{- $dnsDomain := $.kubernetes.networking.dns_domain | default "cluster.local" -}}
        {{- if (index $.hostvars . "internal_ipv4") | empty | not }}
      {{ index $.hostvars . "internal_ipv4" }} {{ $hostname }} {{ printf "%s.%s" $hostname $clusterName }} {{ printf "%s.%s.%s" $hostname $clusterName $dnsDomain }}
        {{- end }}
        {{- if (index $.hostvars . "internal_ipv6") | empty | not }}
      {{ index $.hostvars . "internal_ipv6" }} {{ $hostname }} {{ printf "%s.%s" $hostname $clusterName }} {{ printf "%s.%s.%s" $hostname $clusterName $dnsDomain }}
        {{- end }}
      {{- end }}
      # etcd cluster nodes
      {{- range .groups.etcd | default list }}
        {{- if (index $.hostvars . "internal_ipv4") | empty | not }}
      {{ index $.hostvars . "internal_ipv4" }} {{ index $.hostvars . "hostname" }}
        {{- end }}
        {{- if (index $.hostvars . "internal_ipv6") | empty | not }}
      {{ index $.hostvars . "internal_ipv6" }} {{ index $.hostvars . "hostname" }}
        {{- end }}
      {{- end }}
      # Image registry nodes
      {{- range .groups.image_registry | default list }}
        {{- if (index $.hostvars . "internal_ipv4") | empty | not }}
      {{ index $.hostvars . "internal_ipv4" }} {{ index $.hostvars . "hostname" }}
        {{- end }}
        {{- if (index $.hostvars . "internal_ipv6") | empty | not }}
      {{ index $.hostvars . "internal_ipv6" }} {{ index $.hostvars . "hostname" }}
        {{- end }}
      {{- end }}
      # kubekey image_registry control_plane_endpoint BEGIN
      {{- if and (.image_registry.auth.registry | empty | not) (.image_registry.ha_vip | empty | not) }}
      {{ .image_registry.ha_vip }} {{ .image_registry.auth.registry | splitList "/" | first }}
      {{- else }}
        {{- if .groups.image_registry | empty | not }}
          {{- if (index .hostvars (.groups.image_registry | first) "internal_ipv4") | empty | not }}
      {{ index .hostvars (.groups.image_registry | first) "internal_ipv4" }} {{ .image_registry.auth.registry | splitList "/" | first }}
          {{- end }}
          {{- if (index .hostvars (.groups.image_registry | first) "internal_ipv6") | empty | not }}
      {{ index .hostvars (.groups.image_registry | first) "internal_ipv6" }} {{ .image_registry.auth.registry | splitList "/" | first }}
          {{- end }}
        {{- end }}
      {{- end }}
      # kubekey image_registry control_plane_endpoint END
      # NFS server nodes
      {{- range .groups.nfs | default list }}
        {{- if (index $.hostvars . "internal_ipv4") | empty | not }}
      {{ index $.hostvars . "internal_ipv4" }} {{ index $.hostvars . "hostname" }}
        {{- end }}
        {{- if (index $.hostvars . "internal_ipv6") | empty | not }}
      {{ index $.hostvars . "internal_ipv6" }} {{ index $.hostvars . "hostname" }}
        {{- end }}
      {{- end }}
      # kubekey hosts END
      EOF
    name: command
  name: DNS | Ensure local DNS entries are up-to-date
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: /etc/hosts
  phase: Success
