apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: playbooks/hook
  creationTimestamp: "2026-05-17T20:00:45Z"
  generateName: install-4s8v4-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:ignoreError: {}
        f:module:
          f:args:
            f:dest: {}
            f:mode: {}
            f:src: {}
          f:name: {}
        f:name: {}
        f:register: {}
    manager: kk
    operation: Update
    time: "2026-05-17T20:00:45Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T20:00:49Z"
  name: install-4s8v4-kf5dn
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: install-4s8v4
    uid: a4c16473-6e72-4f19-b0b1-083ac3106725
  resourceVersion: "3"
  uid: a7b658b7-5fe1-46bd-baed-93f89529e0a6
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  ignoreError: true
  loop: null
  module:
    args:
      dest: /etc/kubekey/scripts/pre_install_{{ .inventory_hostname }}.sh
      mode: 493
      src: '{{ .work_dir }}/scripts/pre_install_{{ .inventory_hostname }}.sh'
    name: copy
  name: Pre | Copy pre-installation scripts to remote hosts
  register: pre_install_copy_result
status:
  hostResults:
  - error: module run failed
    host: 47-253-179-114
    loopResults:
    - error: 'stat /mnt/e/Openclaw/kk-console/kubekey/scripts/pre_install_47-253-179-114.sh:
        no such file or directory'
      item: null
      stdErr: failed to stat absolute path
      stdout: failed
  phase: Ignored
