apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/precheck/image-registry/network
  creationTimestamp: "2026-05-17T18:10:26Z"
  generateName: install-pdg24-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args: {}
          f:name: {}
        f:name: {}
        f:register: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T18:10:26Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T18:10:27Z"
  name: install-pdg24-bbqvh
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: install-pdg24
    uid: 059d5cb2-ba8b-4d75-bc6d-970534ef18f3
  resourceVersion: "3"
  uid: ba49df80-7636-43cc-9494-4820e21bd19b
spec:
  DelegateTo: ""
  hosts:
  - localhost
  loop: null
  module:
    args: |
      if {{ .cri.cert.check.cmd }} ; then
          echo "true"
      else
          echo "false"
      fi
    name: command
  name: Cert | Exec check shell with input certs
  register: cert_check_input_cert_result
  when:
  - '{{ .inventory_hostname | eq "localhost" }}'
status:
  hostResults:
  - host: localhost
    loopResults:
    - item: null
      stdout: |
        true
  phase: Success
