apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: playbooks/hook
  creationTimestamp: "2026-05-17T20:20:45Z"
  generateName: install-j7l5w-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args: {}
          f:name: {}
        f:name: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T20:20:45Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T20:20:45Z"
  name: install-j7l5w-mlq2w
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: install-j7l5w
    uid: 4c66d514-df22-41f0-bd1c-723ae58e20e9
  resourceVersion: "3"
  uid: bbd2b90c-11a6-41c7-9aed-9a27987a83da
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args: |
      for file in /etc/kubekey/scripts/pre_install_*.sh; do
        if [ -f "$file" ]; then
          # Make the script executable and run it
          chmod +x "$file"
          "$file"
        fi
      done
    name: command
  name: Pre | Execute pre-installation scripts on remote hosts
  when:
  - '{{ .pre_install_copy_result.error | empty }}'
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: skip
  phase: Success
