apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/defaults
  creationTimestamp: "2026-05-17T19:34:59Z"
  generateName: install-x77kk-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args: {}
          f:name: {}
        f:name: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:34:59Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:34:59Z"
  name: install-x77kk-7npkv
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: install-x77kk
    uid: 5bc90199-9364-4f34-baa0-6c237838b09f
  resourceVersion: "3"
  uid: 373de08e-b2b2-41e4-b252-88d2ea058d17
spec:
  DelegateTo: ""
  hosts:
  - localhost
  loop: null
  module:
    args: |
      if [ -d {{ .tmp_dir }} ]; then
        rm -rf {{ .tmp_dir }}
      fi
      mkdir -m 777 -p {{ .tmp_dir }}
    name: command
  name: Defaults | Reset temporary directory
status:
  hostResults:
  - host: localhost
    loopResults:
    - item: null
  phase: Success
