apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/precheck/inventory
  creationTimestamp: "2026-05-17T20:01:47Z"
  generateName: install-4s8v4-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args:
            f:fail_msg: {}
            f:that: {}
          f:name: {}
        f:name: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T20:01:47Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T20:01:47Z"
  name: install-4s8v4-g65xr
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: install-4s8v4
    uid: a4c16473-6e72-4f19-b0b1-083ac3106725
  resourceVersion: "3"
  uid: c594d138-db14-4432-b901-2bdf9fa5df4a
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args:
      fail_msg: The Kubernetes inventory groups "k8s_cluster" and "kube_control_plane"
        must not be empty. Please ensure both groups are present and correctly specified
        in your inventory file.
      that:
      - .groups.k8s_cluster | empty | not
      - .groups.kube_control_plane | empty | not
    name: assert
  name: Inventory | Kubernetes groups must not be empty
  when:
  - '{{ .inventory_hostname | eq "localhost" }}'
  - '{{ .kubernetes.kube_version | empty | not }}'
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: skip
  phase: Success
