apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/native/repository
  creationTimestamp: "2026-05-17T20:21:54Z"
  generateName: install-j7l5w-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args:
            f:sp_version: {}
          f:name: {}
        f:name: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T20:21:54Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T20:21:54Z"
  name: install-j7l5w-wgbzn
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: install-j7l5w
    uid: 4c66d514-df22-41f0-bd1c-723ae58e20e9
  resourceVersion: "3"
  uid: d8c19aa1-1f89-4497-ab0f-945cfa98d928
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args:
      sp_version: '{{- if .os.release.VERSION | contains "Tercel" }} SP1 {{- else
        if .os.release.VERSION | contains "Sword" }} SP2 {{- else if .os.release.VERSION
        | contains "Lance" }} SP3 {{- else if .os.release.VERSION | contains "Halberd"
        }} SP3-2403 {{- end -}}'
    name: set_fact
  name: Repository | Check system version when use Kylin
  when:
  - '{{or (.groups.k8s_cluster | default list | has .inventory_hostname) (.groups.image_registry
    | default list | has .inventory_hostname)}}'
  - '{{ .os.release.ID | unquote | eq "kylin" }}'
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: skip
  phase: Success
