apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/defaults
  creationTimestamp: "2026-05-17T20:01:42Z"
  generateName: install-4s8v4-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:ignoreError: {}
        f:module:
          f:args: {}
          f:name: {}
        f:name: {}
        f:register: {}
        f:register_type: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T20:01:42Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T20:01:47Z"
  name: install-4s8v4-z9wnb
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: install-4s8v4
    uid: a4c16473-6e72-4f19-b0b1-083ac3106725
  resourceVersion: "3"
  uid: f289a795-6b24-469f-917d-9ff6f8708cae
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  ignoreError: true
  loop: null
  module:
    args: etcd --version
    name: command
  name: Defaults | Get installed etcd version
  register: etcd_install_version
  register_type: yaml
  when:
  - '{{ .groups.etcd | has .inventory_hostname }}'
status:
  hostResults:
  - error: module run failed
    host: 47-253-179-114
    loopResults:
    - error: Process exited with status 127
      item: null
      stdout: '/bin/bash: line 1: etcd: command not found'
  phase: Ignored
