apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/native/repository
  creationTimestamp: "2026-05-17T20:14:39Z"
  generateName: install-dzxqf-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args:
            f:iso_type: {}
          f:name: {}
        f:name: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T20:14:39Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T20:14:40Z"
  name: install-dzxqf-grsjs
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: install-dzxqf
    uid: 6a2be465-0ba6-4e6a-ab84-ba95c503a3dd
  resourceVersion: "3"
  uid: d280d97c-ed45-4144-a609-6702ee3ba7bb
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args:
      iso_type: '{{- if .os.release.ID_LIKE | eq "debian" }} debs {{- else  }} rpms
        {{- end -}}'
    name: set_fact
  name: Repository | Define the package file type by system info
  when:
  - '{{or (.groups.k8s_cluster | default list | has .inventory_hostname) (.groups.image_registry
    | default list | has .inventory_hostname)}}'
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: success
  phase: Success
