apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/defaults
  creationTimestamp: "2026-05-17T20:14:11Z"
  generateName: install-dzxqf-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:ignoreError: {}
        f:module:
          f:args: {}
          f:name: {}
        f:name: {}
        f:register: {}
        f:register_type: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T20:14:11Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T20:14:17Z"
  name: install-dzxqf-w9x5b
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: install-dzxqf
    uid: 6a2be465-0ba6-4e6a-ab84-ba95c503a3dd
  resourceVersion: "3"
  uid: 1d6c4d6b-fafa-4ae3-b4de-92eba0ecf577
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  ignoreError: true
  loop: null
  module:
    args: etcd --version
    name: command
  name: Defaults | Get installed etcd version
  register: etcd_install_version
  register_type: yaml
  when:
  - '{{ .groups.etcd | has .inventory_hostname }}'
status:
  hostResults:
  - error: module run failed
    host: 47-253-179-114
    loopResults:
    - error: Process exited with status 127
      item: null
      stdout: '/bin/bash: line 1: etcd: command not found'
  phase: Ignored
