apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/defaults
  creationTimestamp: "2026-05-17T17:53:19Z"
  generateName: install-8g6zv-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:ignoreError: {}
        f:module:
          f:args: {}
          f:name: {}
        f:name: {}
        f:register: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T17:53:19Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T17:53:19Z"
  name: install-8g6zv-f4qkc
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: install-8g6zv
    uid: 66d47053-b913-464d-8a85-4d05c9a55bbc
  resourceVersion: "3"
  uid: 45e1ed77-f59a-449d-b557-27b57607fc7b
spec:
  DelegateTo: ""
  hosts:
  - localhost
  ignoreError: true
  loop: null
  module:
    args: kubelet --version
    name: command
  name: Defaults | Get installed Kubernetes version
  register: kubernetes_install_version
  when:
  - '{{ .groups.k8s_cluster | has .inventory_hostname }}'
status:
  hostResults:
  - host: localhost
    loopResults:
    - item: null
      stdout: skip
  phase: Success
