apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: playbooks/hook
  creationTimestamp: "2026-05-17T19:06:04Z"
  generateName: install-2gcgf-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args: {}
          f:name: {}
        f:name: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:06:04Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:06:04Z"
  name: install-2gcgf-8rw67
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: install-2gcgf
    uid: 5fed67f6-13b2-46eb-8678-ea26f0dacba5
  resourceVersion: "3"
  uid: 4ba207eb-aa5e-49ca-b3b1-9ca6308a84d6
spec:
  DelegateTo: ""
  hosts:
  - localhost
  loop: null
  module:
    args: |
      for file in /etc/kubekey/scripts/pre_install_*.sh; do
        if [ -f "$file" ]; then
          # Make the script executable and run it
          chmod +x "$file"
          "$file"
        fi
      done
    name: command
  name: Pre | Execute pre-installation scripts on remote hosts
  when:
  - '{{ .pre_install_copy_result.error | empty }}'
status:
  hostResults:
  - host: localhost
    loopResults:
    - item: null
      stdout: skip
  phase: Success
