apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/defaults
  creationTimestamp: "2026-05-17T19:16:15Z"
  generateName: install-zjnzs-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:ignoreError: {}
        f:module:
          f:args: {}
          f:name: {}
        f:name: {}
        f:register: {}
        f:register_type: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:16:15Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:16:15Z"
  name: install-zjnzs-wt8pk
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: install-zjnzs
    uid: 6278e896-5eb8-40b4-839e-b266a3161f24
  resourceVersion: "3"
  uid: 2a37644a-5e68-442f-ab00-34adbe731bb8
spec:
  DelegateTo: ""
  hosts:
  - localhost
  ignoreError: true
  loop: null
  module:
    args: etcd --version
    name: command
  name: Defaults | Get installed etcd version
  register: etcd_install_version
  register_type: yaml
  when:
  - '{{ .groups.etcd | has .inventory_hostname }}'
status:
  hostResults:
  - host: localhost
    loopResults:
    - item: null
      stdout: skip
  phase: Success
