apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/native/init
  creationTimestamp: "2026-05-17T20:22:29Z"
  generateName: install-j7l5w-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:loop: {}
        f:module:
          f:args: {}
          f:name: {}
        f:name: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T20:22:29Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T20:22:34Z"
  name: install-j7l5w-sgmlg
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: install-j7l5w
    uid: 4c66d514-df22-41f0-bd1c-723ae58e20e9
  resourceVersion: "3"
  uid: 8e5b8f97-5080-4261-8303-f1ecdc5e8a1a
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: '{{ .native.localDNS | toJson }}'
  module:
    args: |
      hostnamectl set-hostname {{ .inventory_hostname }} \
        && sed -i '/^127.0.1.1/s/.*/127.0.1.1 {{ .inventory_hostname }}/g' {{ .item }}
    name: command
  name: OS | Set system hostname
  when:
  - '{{.native.set_hostname}}'
  - '{{.inventory_hostname | ne "localhost"}}'
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: /etc/hosts
  phase: Success
