apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/defaults
  creationTimestamp: "2026-05-17T19:44:37Z"
  generateName: install-7dxb4-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args: {}
          f:name: {}
        f:name: {}
        f:register: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:44:37Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:44:37Z"
  name: install-7dxb4-zxngz
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: install-7dxb4
    uid: 976c799c-1b5b-4eba-842f-9da28f053e55
  resourceVersion: "3"
  uid: 44f18266-19fa-432e-82cc-e8b50c2c5fb5
spec:
  DelegateTo: ""
  hosts:
  - localhost
  loop: null
  module:
    args: systemctl show kubelet.service -p LoadState --value
    name: command
  name: Defaults | Get kubelet.service LoadState
  register: kubernetes_install_LoadState
  when:
  - '{{ .groups.k8s_cluster | has .inventory_hostname }}'
status:
  hostResults:
  - host: localhost
    loopResults:
    - item: null
      stdout: skip
  phase: Success
