apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/precheck/os
  creationTimestamp: "2026-05-17T20:01:50Z"
  generateName: install-4s8v4-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args:
            f:fail_msg: {}
            f:that: {}
          f:name: {}
        f:name: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T20:01:50Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T20:01:50Z"
  name: install-4s8v4-4psz2
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: install-4s8v4
    uid: a4c16473-6e72-4f19-b0b1-083ac3106725
  resourceVersion: "3"
  uid: 251530a6-c861-44c5-b5d7-594a3a57d70e
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args:
      fail_msg: The operating system "{{ .os.release.ID }}" is not recognized or supported.
      that: or (.cluster_require.allow_unsupported_distribution_setup) (.cluster_require.supported_os_distributions
        | has .os.release.ID)
    name: assert
  name: OS | Fail if operating system is not supported
  when:
  - '{{ .inventory_hostname | ne "localhost" }}'
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: success
  phase: Success
