apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/precheck/inventory
  creationTimestamp: "2026-05-17T19:35:01Z"
  generateName: install-x77kk-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args:
            f:fail_msg: {}
            f:that: {}
          f:name: {}
        f:name: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:35:01Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:35:01Z"
  name: install-x77kk-d4r6j
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: install-x77kk
    uid: 5bc90199-9364-4f34-baa0-6c237838b09f
  resourceVersion: "3"
  uid: c899e85a-58fa-4eaf-bad7-6ae96bc71d08
spec:
  DelegateTo: ""
  hosts:
  - localhost
  loop: null
  module:
    args:
      fail_msg: The Kubernetes inventory groups "k8s_cluster" and "kube_control_plane"
        must not be empty. Please ensure both groups are present and correctly specified
        in your inventory file.
      that:
      - .groups.k8s_cluster | empty | not
      - .groups.kube_control_plane | empty | not
    name: assert
  name: Inventory | Kubernetes groups must not be empty
  when:
  - '{{ .inventory_hostname | eq "localhost" }}'
  - '{{ .kubernetes.kube_version | empty | not }}'
status:
  hostResults:
  - error: module run failed
    host: localhost
    loopResults:
    - error: The Kubernetes inventory groups "k8s_cluster" and "kube_control_plane"
        must not be empty. Please ensure both groups are present and correctly specified
        in your inventory file.
      item: null
      stdErr: The Kubernetes inventory groups "k8s_cluster" and "kube_control_plane"
        must not be empty. Please ensure both groups are present and correctly specified
        in your inventory file.
      stdout: failed
  phase: Failed
