apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/precheck/inventory
  creationTimestamp: "2026-05-17T18:02:53Z"
  generateName: install-7pxxh-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args:
            f:fail_msg: {}
            f:that: {}
          f:name: {}
        f:name: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T18:02:53Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T18:02:53Z"
  name: install-7pxxh-prjgs
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: install-7pxxh
    uid: bb1bacb2-655a-4dd4-a90a-0b03ed4b7a71
  resourceVersion: "3"
  uid: 7ba66df8-570a-47ee-95cb-a17386f948d3
spec:
  DelegateTo: ""
  hosts:
  - localhost
  loop: null
  module:
    args:
      fail_msg: The number of etcd nodes must be odd to maintain quorum. The current
        count is {{ .groups.etcd | len }}. Please adjust your inventory so that the
        etcd group contains an odd number of hosts.
      that: (mod (.groups.etcd | len) 2) | eq 1
    name: assert
  name: Inventory | Fail if the number of etcd hosts is even
  when:
  - '{{ .inventory_hostname | eq "localhost" }}'
status:
  hostResults:
  - error: module run failed
    host: localhost
    loopResults:
    - error: 'failed to execute template ''{{(mod (.groups.etcd | len) 2) | eq 1}}'':
        template: kubekey:1:23: executing "kubekey" at <len>: error calling len: reflect:
        call of reflect.Value.Type on zero Value'
      item: null
      stdErr: failed to parse argument of that
      stdout: failed
  phase: Failed
