apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: playbooks/hook
  creationTimestamp: "2026-05-17T17:53:17Z"
  generateName: install-8g6zv-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:ignoreError: {}
        f:module:
          f:args:
            f:dest: {}
            f:mode: {}
            f:src: {}
          f:name: {}
        f:name: {}
        f:register: {}
    manager: kk
    operation: Update
    time: "2026-05-17T17:53:17Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T17:53:17Z"
  name: install-8g6zv-9hnz6
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: install-8g6zv
    uid: 66d47053-b913-464d-8a85-4d05c9a55bbc
  resourceVersion: "3"
  uid: 8354a7b4-299e-42fe-8118-fbd101814e85
spec:
  DelegateTo: ""
  hosts:
  - localhost
  ignoreError: true
  loop: null
  module:
    args:
      dest: /etc/kubekey/scripts/pre_install_{{ .inventory_hostname }}.sh
      mode: 493
      src: '{{ .work_dir }}/scripts/pre_install_{{ .inventory_hostname }}.sh'
    name: copy
  name: Pre | Copy pre-installation scripts to remote hosts
  register: pre_install_copy_result
status:
  hostResults:
  - error: module run failed
    host: localhost
    loopResults:
    - error: 'stat /mnt/e/Openclaw/kk-console/kubekey/scripts/pre_install_localhost.sh:
        no such file or directory'
      item: null
      stdErr: failed to stat absolute path
      stdout: failed
  phase: Ignored
