apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/defaults
  creationTimestamp: "2026-05-17T19:38:03Z"
  generateName: install-xvdzz-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args:
            f:binary_type: {}
          f:name: {}
        f:name: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:38:03Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:38:03Z"
  name: install-xvdzz-276tt
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: install-xvdzz
    uid: a8d81170-efff-42d9-8393-2198d197409c
  resourceVersion: "3"
  uid: bda6b39c-dbc8-4441-a830-5139092fb335
spec:
  DelegateTo: ""
  hosts:
  - localhost
  loop: null
  module:
    args:
      binary_type: '{{- if .transform_architectures.amd64 | has .os.architecture -}}
        amd64 {{- else if .transform_architectures.arm64 | has .os.architecture -}}
        arm64 {{- end -}}'
    name: set_fact
  name: Defaults | Determine operating system architecture for each node
status:
  hostResults:
  - host: localhost
    loopResults:
    - item: null
      stdout: success
  phase: Success
