apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/precheck/kubernetes
  creationTimestamp: "2026-05-17T20:14:27Z"
  generateName: install-dzxqf-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args:
            f:fail_msg: {}
            f:that: {}
          f:name: {}
        f:name: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T20:14:27Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T20:14:27Z"
  name: install-dzxqf-m7zsh
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: install-dzxqf
    uid: 6a2be465-0ba6-4e6a-ab84-ba95c503a3dd
  resourceVersion: "3"
  uid: 9bc48253-4f47-4519-b069-2be32d1c09b5
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args:
      fail_msg: This version of KubeKey only supports Kubernetes versions greater
        than or equal to {{ .cluster_require.kube_version_min_required }}. You are
        attempting to use version {{ .kubernetes.kube_version }}.
      that:
      - .kubernetes.kube_version | empty | not
      - .kubernetes.kube_version | semverCompare (printf ">=%s" .cluster_require.kube_version_min_required)
    name: assert
  name: Kubernetes | Fail if unsupported Kubernetes version
  when:
  - '{{ .groups.k8s_cluster | default list | has .inventory_hostname }}'
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: success
  phase: Success
