apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/precheck/network
  creationTimestamp: "2026-05-17T20:21:43Z"
  generateName: install-j7l5w-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args:
            f:fail_msg: {}
            f:that: {}
          f:name: {}
        f:name: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T20:21:43Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T20:21:43Z"
  name: install-j7l5w-l6jrs
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: install-j7l5w
    uid: 4c66d514-df22-41f0-bd1c-723ae58e20e9
  resourceVersion: "3"
  uid: 4f706258-a86c-4822-89bc-4cd1154dc7ab
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args:
      fail_msg: Dual-stack pod networking is only supported in Kubernetes v1.20.0
        or newer.
      that:
      - .kubernetes.kube_version | semverCompare ">=v1.20.0"
      - .cni.pod_cidr | splitList "," | first | ipFamily | eq "IPv4"
      - .cni.pod_cidr | splitList "," | last | ipFamily | eq "IPv6"
    name: assert
  name: Network | Ensure pod networking is properly configured for dual-stack
  when:
  - '{{ .inventory_hostname | ne "localhost" }}'
  - '{{.cni.pod_cidr | empty | not}}'
  - '{{.cni.pod_cidr | splitList "," | len | eq 2}}'
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: skip
  phase: Success
