apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/precheck/cni
  creationTimestamp: "2026-05-17T20:01:49Z"
  generateName: install-4s8v4-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args:
            f:calico_ver: {}
          f:name: {}
        f:name: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T20:01:49Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T20:01:49Z"
  name: install-4s8v4-hlc8b
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: install-4s8v4
    uid: a4c16473-6e72-4f19-b0b1-083ac3106725
  resourceVersion: "3"
  uid: 0bac2ba5-755f-4992-bcfb-cb14549bb085
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args:
      calico_ver: '{{ .cni.calico_version | default .calico_version }}'
    name: set_fact
  name: CNI | Set calico version from config or defaults
  when:
  - '{{ .inventory_hostname | eq "localhost" }}'
  - '{{ .cni.type | eq "calico" }}'
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: skip
  phase: Success
