apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/native/repository
  creationTimestamp: "2026-05-17T20:21:55Z"
  generateName: install-j7l5w-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:ignoreError: {}
        f:module:
          f:args:
            f:dest: {}
            f:src: {}
          f:name: {}
        f:name: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T20:21:55Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T20:22:01Z"
  name: install-j7l5w-jzwbt
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: install-j7l5w
    uid: 4c66d514-df22-41f0-bd1c-723ae58e20e9
  resourceVersion: "3"
  uid: cb694ad5-939e-4d9d-be25-b6a0a5086f87
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  ignoreError: true
  loop: null
  module:
    args:
      dest: '{{ .tmp_dir }}/repository.iso'
      src: '{{ .binary_dir }}/repository/{{ .iso_name }}'
    name: copy
  name: Repository | Copy local repository ISO file
  when:
  - '{{or (.groups.k8s_cluster | default list | has .inventory_hostname) (.groups.image_registry
    | default list | has .inventory_hostname)}}'
status:
  hostResults:
  - error: module run failed
    host: 47-253-179-114
    loopResults:
    - error: 'stat /mnt/e/Openclaw/kk-console/kubekey/kubekey/repository/ubuntu-"24.04"-debs-amd64.iso:
        no such file or directory'
      item: null
      stdErr: failed to stat absolute path
      stdout: failed
  phase: Ignored
