apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  creationTimestamp: "2026-05-17T19:44:36Z"
  generateName: install-7dxb4-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:name: {}
        f:name: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:44:36Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:44:36Z"
  name: install-7dxb4-dzf6c
  namespace: default
  resourceVersion: "3"
  uid: e6dbf900-e8f0-46bd-b8a0-ad5559c9b0a8
spec:
  DelegateTo: ""
  hosts:
  - localhost
  loop: null
  module:
    args: null
    name: setup
  name: gather_facts
status:
  hostResults:
  - host: localhost
    loopResults:
    - item: null
      stdout: success
  phase: Success
