apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/defaults
  creationTimestamp: "2026-05-17T18:02:53Z"
  generateName: install-7pxxh-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args:
            f:hosts: {}
            f:vars:
              .: {}
              f:init_kubernetes_node: {}
          f:name: {}
        f:name: {}
    manager: kk
    operation: Update
    time: "2026-05-17T18:02:53Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T18:02:53Z"
  name: install-7pxxh-d5zcx
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: install-7pxxh
    uid: bb1bacb2-655a-4dd4-a90a-0b03ed4b7a71
  resourceVersion: "3"
  uid: d2005f92-ab0b-4412-a345-a61b589b62b7
spec:
  DelegateTo: ""
  hosts:
  - localhost
  loop: null
  module:
    args:
      hosts: k8s_cluster
      vars:
        init_kubernetes_node: |-
          {{- $initNodes := list -}} {{- $notInitNodes := list -}} {{- range .groups.kube_control_plane -}}
            {{- if index $.hostvars . "kubernetes_install_LoadState" "stdout" | eq "loaded" -}}
              {{- $initNodes = append $initNodes . -}}
            {{- else if index $.hostvars . "kubernetes_install_LoadState" "stdout" | eq "not-found" -}}
              {{- $notInitNodes = append $notInitNodes . -}}
            {{- end -}}
          {{- end -}} {{- if $initNodes | len | eq 1 -}} {{ $initNodes | first }} {{- else if $initNodes | len | lt 1 -}} {{ index $initNodes (randInt 0 ((sub ($initNodes | len) 1) | int)) }} {{- else if $notInitNodes | len | eq 1 -}} {{ $notInitNodes | first }} {{- else if $notInitNodes | len | lt 1 -}} {{ index $notInitNodes (randInt 0 ((sub ($notInitNodes | len) 1) | int)) }} {{- end -}}
    name: add_hostvars
  name: Defaults | Select the initialization node for the cluster
status:
  hostResults:
  - host: localhost
    loopResults:
    - item: null
      stdout: success
  phase: Success
