apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  creationTimestamp: "2026-05-17T19:10:15Z"
  generateName: precheck-kubernetes-4v49v-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:name: {}
        f:name: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:10:15Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:10:29Z"
  name: precheck-kubernetes-4v49v-cjbx7
  namespace: default
  resourceVersion: "3"
  uid: 53d6760c-23cc-434d-b30b-cbfc04836e19
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args: null
    name: setup
  name: gather_facts
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: success
  phase: Success
