apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/precheck/image-registry/network
  creationTimestamp: "2026-05-17T19:42:00Z"
  generateName: precheck-kubernetes-w62fx-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args: {}
          f:name: {}
        f:name: {}
        f:register: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:42:00Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:42:00Z"
  name: precheck-kubernetes-w62fx-bvzhl
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: precheck-kubernetes-w62fx
    uid: d2ce7bae-0829-4c51-ade4-10e84f0edba3
  resourceVersion: "3"
  uid: b4a2b540-845f-4a9a-aa1e-d3019780ef2b
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args: |
      if {{ .cri.cert.check.cmd }} ; then
          echo "true"
      else
          echo "false"
      fi
    name: command
  name: Cert | Exec check shell with input certs
  register: cert_check_input_cert_result
  when:
  - '{{ .inventory_hostname | eq "localhost" }}'
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: skip
  phase: Success
