apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/precheck/os
  creationTimestamp: "2026-05-17T19:36:45Z"
  generateName: precheck-kubernetes-9744j-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args:
            f:fail_msg: {}
            f:that: {}
          f:name: {}
        f:name: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:36:45Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:36:46Z"
  name: precheck-kubernetes-9744j-jjzz2
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: precheck-kubernetes-9744j
    uid: 972ba954-5048-4cd6-ad5a-44e09d4336b1
  resourceVersion: "3"
  uid: 29ed65fc-a90b-4a99-9d98-4e8b06ddfeab
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args:
      fail_msg: The system architecture "{{ .os.architecture }}" is not supported.
      that: .cluster_require.supported_architectures | has .os.architecture
    name: assert
  name: OS | Fail if architecture is not supported
  when:
  - '{{ .inventory_hostname | ne "localhost" }}'
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: success
  phase: Success
