apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/precheck/os
  creationTimestamp: "2026-05-17T20:07:09Z"
  generateName: precheck-kubernetes-5wrms-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args:
            f:fail_msg: {}
            f:that: {}
          f:name: {}
        f:name: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T20:07:09Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T20:07:09Z"
  name: precheck-kubernetes-5wrms-9g6nm
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: precheck-kubernetes-5wrms
    uid: f77fc1b4-abb9-47e6-8f66-79ebbb7db5c9
  resourceVersion: "3"
  uid: ca726e9d-4803-442e-a1f5-37b85f87a839
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args:
      fail_msg: 'The kernel version "{{ .os.kernel_version }}" is too old. Minimum
        required version: {{ .cluster_require.min_kernel_version }}.'
      that: .os.kernel_version | splitList "-" | first | semverCompare (printf ">=%s"
        .cluster_require.min_kernel_version)
    name: assert
  name: OS | Fail if kernel version is too old
  when:
  - '{{ .inventory_hostname | ne "localhost" }}'
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: success
  phase: Success
