apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  creationTimestamp: "2026-05-17T18:23:00Z"
  generateName: precheck-kubernetes-4pkq5-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:name: {}
        f:name: {}
    manager: kk
    operation: Update
    time: "2026-05-17T18:23:00Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T18:23:28Z"
  name: precheck-kubernetes-4pkq5-7sx64
  namespace: default
  resourceVersion: "3"
  uid: 8aceb14a-9804-48cb-a889-4d8570ccedb3
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args: null
    name: setup
  name: gather_facts
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: success
  phase: Success
