apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/precheck/cni
  creationTimestamp: "2026-05-17T20:12:08Z"
  generateName: precheck-kubernetes-6kt77-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args:
            f:fail_msg: {}
            f:that: {}
          f:name: {}
        f:name: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T20:12:08Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T20:12:08Z"
  name: precheck-kubernetes-6kt77-xk8kl
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: precheck-kubernetes-6kt77
    uid: db636db9-195b-48ff-886d-bd20f7af0dc1
  resourceVersion: "3"
  uid: bbe9f1bc-058d-4895-bd0d-45c819630a77
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args:
      fail_msg: The selected Cilium version ({{ .cni.kubeovn_version }}) is not allowed
        for the selected Kubernetes version ({{ .kubernetes.kube_version }}).
      that: index .cluster_require.kubeovn_allowed_versions (slice (.cni.kubeovn_version
        | splitList ".") 0 2 | join ".") | has (slice (.kubernetes.kube_version |
        splitList ".") 0 2 | join ".")
    name: assert
  name: CNI | Validate kubeovn version is allowed for the selected Kubernetes version
  when:
  - '{{ .inventory_hostname | eq "localhost" }}'
  - '{{ .cni.type | eq "kubeovn" }}'
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: skip
  phase: Success
