apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/defaults
  creationTimestamp: "2026-05-17T19:42:24Z"
  generateName: precheck-kubernetes-rrgjp-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args: {}
          f:name: {}
        f:name: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:42:24Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:42:34Z"
  name: precheck-kubernetes-rrgjp-fpd4j
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: precheck-kubernetes-rrgjp
    uid: 495ba08b-6282-42fe-b31f-cdd6c3fae087
  resourceVersion: "3"
  uid: 5df7bb5c-aa66-4466-a0ce-2fbf7fe0c8ea
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args: |
      if [ -d {{ .tmp_dir }} ]; then
        rm -rf {{ .tmp_dir }}
      fi
      mkdir -m 777 -p {{ .tmp_dir }}
    name: command
  name: Defaults | Reset temporary directory
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
  phase: Success
