apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/precheck/image-registry/network
  creationTimestamp: "2026-05-17T19:59:54Z"
  generateName: precheck-kubernetes-xvgbp-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args:
            f:hosts: {}
            f:vars:
              .: {}
              f:image_registry:
                .: {}
                f:auth:
                  .: {}
                  f:ca_file: {}
                  f:cert_file: {}
                  f:key_file: {}
          f:name: {}
        f:name: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:59:54Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:59:54Z"
  name: precheck-kubernetes-xvgbp-g5xwp
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: precheck-kubernetes-xvgbp
    uid: 8e47e037-fab5-4d53-abaf-a2610fb976de
  resourceVersion: "3"
  uid: 291ec49f-85eb-4da9-89df-af3de7115b61
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args:
      hosts: all
      vars:
        image_registry:
          auth:
            ca_file: '{{ .binary_dir }}/pki/root.crt'
            cert_file: '{{ .binary_dir }}/pki/image_registry.crt'
            key_file: '{{ .binary_dir }}/pki/image_registry.key'
    name: add_hostvars
  name: Cert | Set auth ca
  when:
  - '{{ .inventory_hostname | eq "localhost" }}'
  - '{{ .cert_check_self_cert_result.stdout | eq "true" }}'
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: skip
  phase: Success
