apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/defaults
  creationTimestamp: "2026-05-17T17:51:40Z"
  generateName: precheck-kubernetes-fsw6b-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args: {}
          f:name: {}
        f:name: {}
        f:register: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T17:51:40Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T17:51:40Z"
  name: precheck-kubernetes-fsw6b-jm42b
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: precheck-kubernetes-fsw6b
    uid: 354caef4-28c0-4478-9fda-1913abf2973a
  resourceVersion: "3"
  uid: a803268b-b8a0-4b0c-8e76-e44166ccc26f
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args: systemctl show etcd.service -p ActiveState --value
    name: command
  name: Defaults | Get etcd.service ActiveState and save to variable
  register: etcd_install_ActiveState
  when:
  - '{{ .groups.etcd | has .inventory_hostname }}'
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: skip
  phase: Success
