apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  creationTimestamp: "2026-05-17T19:43:51Z"
  generateName: precheck-kubernetes-njq6g-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:name: {}
        f:name: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:43:51Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:44:07Z"
  name: precheck-kubernetes-njq6g-4dmkc
  namespace: default
  resourceVersion: "3"
  uid: 28e56485-6861-4d06-bc3d-adb02c6b7e84
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args: null
    name: setup
  name: gather_facts
status:
  hostResults:
  - error: module run failed
    host: 47-253-179-114
    loopResults:
    - error: 'failed to write host 47-253-179-114 variable to source: failed to create
        file "47-253-179-114.yaml": open /mnt/e/Openclaw/kk-console/kubekey/runtime/kubekey.kubesphere.io/v1/playbooks/default/precheck-kubernetes-njq6g/variable/47-253-179-114.yaml:
        no such file or directory'
      item: null
      stdErr: failed to merge setup variable
      stdout: failed
  phase: Failed
