apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/defaults
  creationTimestamp: "2026-05-17T20:14:20Z"
  generateName: precheck-kubernetes-kz8kw-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args: {}
          f:name: {}
        f:name: {}
        f:register: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T20:14:20Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T20:14:24Z"
  name: precheck-kubernetes-kz8kw-whgx2
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: precheck-kubernetes-kz8kw
    uid: 2cfaa148-52d6-41cd-a507-3de41aeaa207
  resourceVersion: "3"
  uid: 7cb599cb-a298-4325-bc3b-ddcfbb58508a
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args: systemctl show etcd.service -p LoadState --value
    name: command
  name: Defaults | Get etcd.service LoadState and save to variable
  register: etcd_install_LoadState
  when:
  - '{{ .groups.etcd | has .inventory_hostname }}'
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: not-found
  phase: Success
