apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/precheck/cni
  creationTimestamp: "2026-05-17T19:49:16Z"
  generateName: precheck-kubernetes-w7g5v-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args:
            f:calico_ver: {}
          f:name: {}
        f:name: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:49:16Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:49:16Z"
  name: precheck-kubernetes-w7g5v-kmm69
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: precheck-kubernetes-w7g5v
    uid: 55f4f465-66a4-4124-82c1-7263c23510ff
  resourceVersion: "3"
  uid: c2ae165b-64cf-4092-8fc4-c60696ad5bfe
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args:
      calico_ver: '{{ .cni.calico_version | default .calico_version }}'
    name: set_fact
  name: CNI | Set calico version from config or defaults
  when:
  - '{{ .inventory_hostname | eq "localhost" }}'
  - '{{ .cni.type | eq "calico" }}'
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: skip
  phase: Success
