apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/precheck/cni
  creationTimestamp: "2026-05-17T19:36:45Z"
  generateName: precheck-kubernetes-9744j-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args:
            f:fail_msg: {}
            f:that: {}
          f:name: {}
        f:name: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:36:45Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:36:45Z"
  name: precheck-kubernetes-9744j-s259q
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: precheck-kubernetes-9744j
    uid: 972ba954-5048-4cd6-ad5a-44e09d4336b1
  resourceVersion: "3"
  uid: 5725e397-7f2b-4667-9d61-992eb4b613cb
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args:
      fail_msg: Spiderpool should be used with calico or cilium.
      that: or (.cni.type | eq "calico") (.cni.type | eq "cilium")
    name: assert
  name: CNI | Ensure Spiderpool is only configured alongside Calico or Cilium networking
    plugins
  when:
  - '{{ .inventory_hostname | eq "localhost" }}'
  - '{{ .cni.multi_cni | eq "spiderpool" }}'
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: skip
  phase: Success
