apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/precheck/cni
  creationTimestamp: "2026-05-17T19:34:00Z"
  generateName: precheck-kubernetes-ssvjq-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args:
            f:fail_msg: {}
            f:that: {}
          f:name: {}
        f:name: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:34:00Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:34:01Z"
  name: precheck-kubernetes-ssvjq-tc95b
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: precheck-kubernetes-ssvjq
    uid: ac4a79c4-a5f9-4aa1-9c56-be63a0e1d425
  resourceVersion: "3"
  uid: 481df8b3-fea7-4170-ae65-763fe6aa00b9
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args:
      fail_msg: 'The selected Calico version ({{ .cni.calico_version }}) is not allowed
        for the selected Kubernetes version ({{ .kubernetes.kube_version }}). '
      that: index .cluster_require.calico_allowed_versions (slice (.calico_ver | splitList
        ".") 0 2 | join ".") | has (slice (.kubernetes.kube_version | splitList ".")
        0 2 | join ".")
    name: assert
  name: CNI | Validate calico version is allowed for the selected Kubernetes version
  when:
  - '{{ .inventory_hostname | eq "localhost" }}'
  - '{{ .calico_ver | empty | not }}'
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: skip
  phase: Success
