apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/defaults
  creationTimestamp: "2026-05-17T19:41:54Z"
  generateName: precheck-kubernetes-w62fx-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:ignoreError: {}
        f:module:
          f:args: {}
          f:name: {}
        f:name: {}
        f:register: {}
        f:register_type: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:41:54Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:41:59Z"
  name: precheck-kubernetes-w62fx-vzz48
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: precheck-kubernetes-w62fx
    uid: d2ce7bae-0829-4c51-ade4-10e84f0edba3
  resourceVersion: "3"
  uid: 3a3b8757-6a7f-4790-9022-b8b507e56bbe
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  ignoreError: true
  loop: null
  module:
    args: etcd --version
    name: command
  name: Defaults | Get installed etcd version
  register: etcd_install_version
  register_type: yaml
  when:
  - '{{ .groups.etcd | has .inventory_hostname }}'
status:
  hostResults:
  - error: module run failed
    host: 47-253-179-114
    loopResults:
    - error: Process exited with status 127
      item: null
      stdout: '/bin/bash: line 1: etcd: command not found'
  phase: Ignored
