apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/precheck/image-registry/network
  creationTimestamp: "2026-05-17T19:59:20Z"
  generateName: precheck-kubernetes-wcz7c-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args: {}
          f:name: {}
        f:name: {}
        f:register: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:59:20Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:59:20Z"
  name: precheck-kubernetes-wcz7c-9g2pq
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: precheck-kubernetes-wcz7c
    uid: 1afcf250-955a-4ecd-9480-abc54ad95266
  resourceVersion: "3"
  uid: b5d52047-80ae-42cd-9d58-154a83ac269d
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args: |
      if {{ .cri.cert.check.cmd }} ; then
          echo "true"
      else
          echo "false"
      fi
    name: command
  name: Cert | Exec check shell with input certs
  register: cert_check_input_cert_result
  when:
  - '{{ .inventory_hostname | eq "localhost" }}'
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: skip
  phase: Success
