apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/precheck/storageclass
  creationTimestamp: "2026-05-17T19:42:02Z"
  generateName: precheck-kubernetes-w62fx-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args:
            f:fail_msg: {}
            f:that: {}
          f:name: {}
        f:name: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:42:02Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:42:02Z"
  name: precheck-kubernetes-w62fx-p26df
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: precheck-kubernetes-w62fx
    uid: d2ce7bae-0829-4c51-ade4-10e84f0edba3
  resourceVersion: "3"
  uid: 07d07383-cd6e-4e6d-ab7a-cdf63366473b
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args:
      fail_msg: The specified localpv_provisioner_version "{{ .storage_class.localpv_provisioner_version
        }}" is not supported. Please use version 4.1.0 or newer.
      that:
      - .storage_class.localpv_provisioner_version | empty | not
      - .storage_class.localpv_provisioner_version | semverCompare ">=4.0.0"
    name: assert
  name: StorageClass | Fail if localpv provisioner version is unsupported
  when:
  - '{{ .inventory_hostname | eq "localhost" }}'
  - '{{ .storage_class.nfs.enabled }}'
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: skip
  phase: Success
