apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/defaults
  creationTimestamp: "2026-05-17T19:36:34Z"
  generateName: precheck-kubernetes-9744j-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args:
            f:dest: {}
            f:src: {}
          f:name: {}
        f:name: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:36:34Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:36:41Z"
  name: precheck-kubernetes-9744j-9m2jz
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: precheck-kubernetes-9744j
    uid: 972ba954-5048-4cd6-ad5a-44e09d4336b1
  resourceVersion: "3"
  uid: 431d2b84-6803-4535-8417-67379c8c8143
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args:
      dest: '{{ .binary_dir }}/manifests.yaml'
      src: manifests.yaml
    name: template
  name: Defaults | Load default templates download
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: success
  phase: Success
