apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/precheck/cri
  creationTimestamp: "2026-05-17T19:36:44Z"
  generateName: precheck-kubernetes-9744j-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args:
            f:fail_msg: {}
            f:that: {}
          f:name: {}
        f:name: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:36:44Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:36:44Z"
  name: precheck-kubernetes-9744j-z5hrm
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: precheck-kubernetes-9744j
    uid: 972ba954-5048-4cd6-ad5a-44e09d4336b1
  resourceVersion: "3"
  uid: df4456f9-6c9e-478b-bf6a-bb1870e51edc
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args:
      fail_msg: 'The detected containerd version ({{ .containerd_version }}) is below
        the minimum required version: {{ .cluster_require.containerd_min_version_required
        }}.'
      that: .cri.containerd_version | semverCompare (printf ">=%s" .cluster_require.containerd_min_version_required)
    name: assert
  name: CRI | Validate minimum required containerd version
  when:
  - '{{ .inventory_hostname | eq "localhost" }}'
  - '{{.cri.containerd_version | empty | not}}'
  - '{{.cri.container_manager | eq "containerd"}}'
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: skip
  phase: Success
