apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/defaults
  creationTimestamp: "2026-05-17T19:55:07Z"
  generateName: precheck-kubernetes-hzvsv-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args: {}
          f:name: {}
        f:name: {}
        f:register: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:55:07Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:55:07Z"
  name: precheck-kubernetes-hzvsv-f7x55
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: precheck-kubernetes-hzvsv
    uid: a9d4db17-2c2a-4e71-a447-e06329e01a3c
  resourceVersion: "2"
  uid: 09e07028-2887-4e25-9b27-6e818f3c4e67
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args: systemctl show etcd.service -p ActiveState --value
    name: command
  name: Defaults | Get etcd.service ActiveState and save to variable
  register: etcd_install_ActiveState
  when:
  - '{{ .groups.etcd | has .inventory_hostname }}'
status:
  phase: Running
