apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/precheck/inventory
  creationTimestamp: "2026-05-17T19:59:53Z"
  generateName: precheck-kubernetes-xvgbp-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args:
            f:fail_msg: {}
            f:that: {}
          f:name: {}
        f:name: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:59:53Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:59:53Z"
  name: precheck-kubernetes-xvgbp-28tqn
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: precheck-kubernetes-xvgbp
    uid: 8e47e037-fab5-4d53-abaf-a2610fb976de
  resourceVersion: "3"
  uid: cb7ad23d-19b7-4c1d-8c4b-4f5ba7427b5f
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args:
      fail_msg: The etcd inventory group "etcd" must not be empty. Please verify that
        this group is properly defined in your inventory.
      that: .groups.etcd | empty | not
    name: assert
  name: Inventory | etcd group must not be empty
  when:
  - '{{ .inventory_hostname | eq "localhost" }}'
  - '{{ .kubernetes.kube_version | empty | not }}'
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: skip
  phase: Success
