apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/defaults
  creationTimestamp: "2026-05-17T20:06:44Z"
  generateName: precheck-kubernetes-5wrms-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args: {}
          f:name: {}
        f:name: {}
        f:register: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T20:06:44Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T20:06:49Z"
  name: precheck-kubernetes-5wrms-hhwvf
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: precheck-kubernetes-5wrms
    uid: f77fc1b4-abb9-47e6-8f66-79ebbb7db5c9
  resourceVersion: "3"
  uid: 76782ee6-b5e6-42a2-a51f-23e5a688e375
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args: systemctl show kubelet.service -p ActiveState --value
    name: command
  name: Defaults | Get kubelet.service ActiveState
  register: kubernetes_install_ActiveState
  when:
  - '{{ .groups.k8s_cluster | has .inventory_hostname }}'
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: inactive
  phase: Success
