apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/precheck/network
  creationTimestamp: "2026-05-17T17:48:54Z"
  generateName: precheck-kubernetes-fx4ss-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args: {}
          f:name: {}
        f:name: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T17:48:54Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T17:49:08Z"
  name: precheck-kubernetes-fx4ss-ttr8z
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: precheck-kubernetes-fx4ss
    uid: 9d607747-5b59-48df-8c67-2085bb75e5d8
  resourceVersion: "3"
  uid: 6c008ebb-c5b0-43d8-9d3f-766b2237fdad
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args: |
      {{- if .internal_ipv4 | empty | not }}
      if ! ip -o addr show | grep -q {{ .internal_ipv4 }}; then
        echo 'The specified IPv4 address is not assigned to any network interface.' >&2
        exit 1
      fi
      {{- end }}
      {{- if .internal_ipv6 | empty | not }}
      if ! ip -o addr show | grep -q {{ .internal_ipv6 }}; then
        echo 'The specified IPv6 address is not assigned to any network interface.' >&2
        exit 1
      fi
      {{- end }}
    name: command
  name: Network | Ensure required network interfaces are present
  when:
  - '{{ .inventory_hostname | ne "localhost" }}'
status:
  hostResults:
  - error: module run failed
    host: 47-253-179-114
    loopResults:
    - error: Process exited with status 1
      item: null
      stdout: The specified IPv4 address is not assigned to any network interface.
  phase: Failed
