apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/precheck/artifact
  creationTimestamp: "2026-05-17T20:13:23Z"
  generateName: precheck-kubernetes-6g8f4-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args:
            f:fail_msg: {}
            f:that: {}
          f:name: {}
        f:name: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T20:13:23Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T20:13:23Z"
  name: precheck-kubernetes-6g8f4-m7p58
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: precheck-kubernetes-6g8f4
    uid: 479fd769-a347-4b7f-9b09-8f35da707cbe
  resourceVersion: "3"
  uid: ca61bc52-2f4f-41d3-9ed1-9b67c6020209
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args:
      fail_msg: Artifact file '{{ .download.artifact_file }}' does not have the required
        extension '.tgz' or '.tar.gz'.
      that:
      - .download.artifact_file | fileExists
      - or (.download.artifact_file | hasSuffix ".tgz") (.download.artifact_file |
        hasSuffix ".tar.gz")
    name: assert
  name: Artifact | Validate artifact file extension
  when:
  - '{{ .inventory_hostname | eq "localhost" }}'
  - '{{.download.artifact_file | empty | not}}'
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: skip
  phase: Success
