apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/defaults
  creationTimestamp: "2026-05-17T19:42:44Z"
  generateName: precheck-kubernetes-rrgjp-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args: {}
          f:name: {}
        f:name: {}
        f:register: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:42:44Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:42:49Z"
  name: precheck-kubernetes-rrgjp-zzj79
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: precheck-kubernetes-rrgjp
    uid: 495ba08b-6282-42fe-b31f-cdd6c3fae087
  resourceVersion: "3"
  uid: a5cc3683-5764-4236-b469-85055434476c
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args: systemctl show kubelet.service -p LoadState --value
    name: command
  name: Defaults | Get kubelet.service LoadState
  register: kubernetes_install_LoadState
  when:
  - '{{ .groups.k8s_cluster | has .inventory_hostname }}'
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: not-found
  phase: Success
