apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/defaults
  creationTimestamp: "2026-05-17T19:41:16Z"
  generateName: precheck-kubernetes-w62fx-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args: {}
          f:name: {}
        f:name: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:41:16Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:41:22Z"
  name: precheck-kubernetes-w62fx-jnnvc
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: precheck-kubernetes-w62fx
    uid: d2ce7bae-0829-4c51-ade4-10e84f0edba3
  resourceVersion: "3"
  uid: f76f9a4a-02bd-4d83-854f-b483571edf6f
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args: |
      if [ -d {{ .tmp_dir }} ]; then
        rm -rf {{ .tmp_dir }}
      fi
      mkdir -m 777 -p {{ .tmp_dir }}
    name: command
  name: Defaults | Reset temporary directory
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
  phase: Success
