apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  creationTimestamp: "2026-05-17T18:20:54Z"
  generateName: precheck-kubernetes-wfxpk-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:name: {}
        f:name: {}
    manager: kk
    operation: Update
    time: "2026-05-17T18:20:54Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T18:21:32Z"
  name: precheck-kubernetes-wfxpk-gxflx
  namespace: default
  resourceVersion: "3"
  uid: 4a34a71d-8b94-4591-ac77-da3c5d46e51d
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args: null
    name: setup
  name: gather_facts
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: success
  phase: Success
