apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  annotations:
    kubesphere.io/rel-path: roles/precheck/image-registry/network
  creationTimestamp: "2026-05-17T17:23:43Z"
  generateName: precheck-kubernetes-tjs5r-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubesphere.io/rel-path: {}
        f:generateName: {}
        f:ownerReferences: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:args:
            f:cri:
              .: {}
              f:cert:
                .: {}
                f:check:
                  .: {}
                  f:cmd: {}
          f:name: {}
        f:name: {}
        f:when: {}
    manager: kk
    operation: Update
    time: "2026-05-17T17:23:43Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T17:23:43Z"
  name: precheck-kubernetes-tjs5r-gcf84
  namespace: default
  ownerReferences:
  - apiVersion: kubekey.kubesphere.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Playbook
    name: precheck-kubernetes-tjs5r
    uid: f97107bb-82f1-48f2-b0eb-5aafcec5ef0a
  resourceVersion: "3"
  uid: 7dfb2a7e-ee74-4667-a864-1e806b65453c
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args:
      cri:
        cert:
          check:
            cmd: "/etc/kubekey/scripts/check.sh {{ .image_registry.auth.registry |
              splitList \"/\" | first }} \n    {{- if .image_registry.auth.skip_tls_verify
              -}}\n    {{ printf \" --insecure  \" }} \n    {{- end -}}\n    {{- if
              .image_registry.auth.ca_file | empty | not -}}\n    {{ printf \" --ca-file
              %s \" .image_registry.auth.ca_file }}\n    {{- end -}}\n    {{- if .image_registry.auth.cert_file
              | empty | not -}}\n    {{ printf \" --cert-file %s \" .image_registry.auth.cert_file
              }}\n    {{- end -}}\n    {{- if .image_registry.auth.key_file | empty
              | not -}}\n    {{ printf \" --key-file %s \" .image_registry.auth.key_file
              }}\n    {{- end -}}"
    name: set_fact
  name: Cert | Set cert check command
  when:
  - '{{ .inventory_hostname | eq "localhost" }}'
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: skip
  phase: Success
