apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Task
metadata:
  creationTimestamp: "2026-05-17T19:32:55Z"
  generateName: precheck-kubernetes-ssvjq-
  managedFields:
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
      f:spec:
        f:hosts: {}
        f:module:
          f:name: {}
        f:name: {}
    manager: kk
    operation: Update
    time: "2026-05-17T19:32:55Z"
  - apiVersion: kubekey.kubesphere.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:hostResults: {}
        f:phase: {}
    manager: kk
    operation: Update
    subresource: status
    time: "2026-05-17T19:33:12Z"
  name: precheck-kubernetes-ssvjq-fpt5h
  namespace: default
  resourceVersion: "3"
  uid: 09b730c0-b28f-4084-8deb-549326061923
spec:
  DelegateTo: ""
  hosts:
  - 47-253-179-114
  loop: null
  module:
    args: null
    name: setup
  name: gather_facts
status:
  hostResults:
  - host: 47-253-179-114
    loopResults:
    - item: null
      stdout: success
  phase: Success
