- hosts: k8s_cluster
  tasks:
    - name: get not ready node from kubernetes
      command: |
        if kubectl get nodes --no-headers | awk '$2 != "Ready" {printf "%s ", $1}'; then
            echo "kubernetes is ready"
        else
            echo "kubernetes is not ready" >&2
        fi